// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package firewall

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type programPeerRuleKey struct {
	_     structs.HostLayout
	SrcIp uint32
	DstIp uint32
	Port  uint16
	Proto uint8
	Pad   uint8
}

// loadProgram returns the embedded CollectionSpec for program.
func loadProgram() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProgramBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load program: %w", err)
	}

	return spec, err
}

// loadProgramObjects loads program and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*programObjects
//	*programPrograms
//	*programMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProgramObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadProgram()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// programSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type programSpecs struct {
	programProgramSpecs
	programMapSpecs
	programVariableSpecs
}

// programProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type programProgramSpecs struct {
	Filter *ebpf.ProgramSpec `ebpf:"filter"`
}

// programMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type programMapSpecs struct {
	PeerRules *ebpf.MapSpec `ebpf:"peer_rules"`
}

// programVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type programVariableSpecs struct {
	FilterMask *ebpf.VariableSpec `ebpf:"filter_mask"`
	FilterNet  *ebpf.VariableSpec `ebpf:"filter_net"`
}

// programObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProgramObjects or ebpf.CollectionSpec.LoadAndAssign.
type programObjects struct {
	programPrograms
	programMaps
	programVariables
}

func (o *programObjects) Close() error {
	return _ProgramClose(
		&o.programPrograms,
		&o.programMaps,
	)
}

// programMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProgramObjects or ebpf.CollectionSpec.LoadAndAssign.
type programMaps struct {
	PeerRules *ebpf.Map `ebpf:"peer_rules"`
}

func (m *programMaps) Close() error {
	return _ProgramClose(
		m.PeerRules,
	)
}

// programVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProgramObjects or ebpf.CollectionSpec.LoadAndAssign.
type programVariables struct {
	FilterMask *ebpf.Variable `ebpf:"filter_mask"`
	FilterNet  *ebpf.Variable `ebpf:"filter_net"`
}

// programPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProgramObjects or ebpf.CollectionSpec.LoadAndAssign.
type programPrograms struct {
	Filter *ebpf.Program `ebpf:"filter"`
}

func (p *programPrograms) Close() error {
	return _ProgramClose(
		p.Filter,
	)
}

func _ProgramClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed program_bpfeb.o
var _ProgramBytes []byte
